### ISSUE TITLE
Can't craft string mesh

### ISSUE THREAD

**Issue by ghost** [jaminvanderberg/Arcane-Skies#1]
i have a probleme, when i want to craft a string mesh, i get a silk which have the same craft.
![2019-07-16_13 23 56](https://user-images.githubusercontent.com/52279972/61290857-29a00d00-a7cd-11e9-84ac-0c2677fc544b.png)
![2019-07-16_13 24 05](https://user-images.githubusercontent.com/52279972/61290861-2b69d080-a7cd-11e9-9a39-4a2b73caa0fa.png)

**Comment by jaminvanderberg** [comment]
Thanks for your help!

So sorry. I added Erebus after I had already run through the early game and didn't notice the conflict. That pretty much halts the early game. Hopefully I can get  you back on track soon.

I've pushed a new update just now. If you need a real quick fix, you can add the attached string.zs file to the scripts directory.

I removed the string from the middle of the silk recipe. String is a plentiful resource, especially later, so this shouldn't be a big deal.

[string.zip](https://github.com/jaminvanderberg/Arcane-Skies/files/3398531/string.zip)
